import { describe, expect, it } from "vitest";

import { Sha256 } from "@aws-crypto/sha256-js";
import type { PostgresDatabase, SqlClient } from "@navocms/persistence-postgres";
import { HttpRequest } from "@smithy/protocol-http";
import { SignatureV4 } from "@smithy/signature-v4";

import { PostgresMediaUploadIntentSigner, S3CompatibleMediaStorage, type S3Transport, type S3TransportResponse } from "./s3-storage.js";
import { sha256 } from "./storage.js";
import { MEDIA_LIMITS } from "./validation.js";

const scope = { tenantId: "11111111-1111-4111-8111-111111111111", siteId: "22222222-2222-4222-8222-222222222222" };
const now = new Date("2026-08-24T12:00:00.000Z");
const pendingKey = `tenants/${scope.tenantId}/sites/${scope.siteId}/pending/33333333-3333-4333-8333-333333333333`;
const originalOne = `tenants/${scope.tenantId}/sites/${scope.siteId}/originals/${"a".repeat(64)}`;
const originalTwo = `tenants/${scope.tenantId}/sites/${scope.siteId}/originals/${"b".repeat(64)}`;
// Generated by AWS SDK v3's Smithy SignatureV4 on 2026-08-24; this retained
// vector is independently re-derived below, rather than by production code.
const AWS_SDK_V3_SIGV4_VECTOR = "https://r2.example.test/navocms-media/tenants/11111111-1111-4111-8111-111111111111/sites/22222222-2222-4222-8222-222222222222/pending/33333333-3333-4333-8333-333333333333?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIDEXAMPLE%2F20260824%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20260824T120000Z&X-Amz-Expires=120&x-amz-meta-expected-size=42&x-amz-meta-media-type=image%2Fpng&x-amz-meta-sha256=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa&X-Amz-Signature=27bb6633ee98f93e829a13ef70c51b2341ebd0faaf6eccab4af91dcdd7af40eb&X-Amz-SignedHeaders=content-type%3Bhost%3Bif-none-match%3Bx-navocms-upload-intent%3Bx-navocms-upload-ttl";

describe("S3-compatible media storage contract", () => {
  it("uses conditional immutable PUT and rejects a foreign key before transport", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport);
    await storage.putImmutable({ key: pendingKey, bytes: bytes("one"), mediaType: "image/png" });
    expect(transport.requests[0]).toMatchObject({ method: "PUT", key: pendingKey, headers: { "if-none-match": "*" } });
    await expect(storage.head(pendingKey.replace(scope.siteId, "44444444-4444-4444-8444-444444444444"))).rejects.toThrow("SCOPE");
    expect(transport.requests).toHaveLength(1);
  });

  it("treats a conditional conflict as a safe replay only for exact persisted bytes and MIME", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport); const body = bytes("same");
    transport.responses.push(response(412), response(200, metadata(body)), response(200, {}, stream(body)));
    await expect(storage.putImmutable({ key: pendingKey, bytes: body, mediaType: "image/png" })).resolves.toBeUndefined();
    transport.responses.push(response(412), response(200, metadata(body, "image/jpeg")), response(200, {}, stream(body)));
    await expect(storage.putImmutable({ key: pendingKey, bytes: body, mediaType: "image/png" })).rejects.toThrow("IMMUTABLE");
  });

  it("does not GET an oversized HEAD and aborts a lying oversized stream", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport); const body = bytes("payload");
    transport.responses.push(response(200, metadata(body)));
    await expect(storage.read(pendingKey, body.byteLength - 1)).rejects.toThrow("READ_LIMIT");
    expect(transport.requests.map(({ method }) => method)).toEqual(["HEAD"]);
    let aborted = 0;
    transport.responses.push(response(200, metadata(body)), response(200, {}, stream(body, bytes("overflow")), () => { aborted += 1; }));
    await expect(storage.read(pendingKey, body.byteLength)).rejects.toThrow("READ_LIMIT");
    expect(aborted).toBeGreaterThan(0);
    expect(transport.requests.at(-1)?.headers).toMatchObject({ range: `bytes=0-${body.byteLength}` });
  });

  it("normalizes thrown transports and thrown body iterators and cancels the response", async () => {
    const throwing: S3Transport = { async request() { throw new Error("https://secret.example/token"); } };
    await expect(adapter(throwing).head(pendingKey)).rejects.toThrow("STORAGE_PROVIDER_UNAVAILABLE");
    const transport = new RecordingTransport(); const storage = adapter(transport); let aborted = 0;
    transport.responses.push(response(200, metadata(bytes("one"))), response(200, {}, brokenStream(), () => { aborted += 1; }));
    await expect(storage.read(pendingKey, 3)).rejects.toThrow("STORAGE_PROVIDER_UNAVAILABLE");
    expect(aborted).toBeGreaterThan(0);
  });

  it("preserves verified metadata through copy/delete/restore and enforces the stored reclaim deadline", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport); const body = bytes("one"); const deadline = new Date("2026-08-24T12:05:00.000Z");
    transport.responses.push(response(200, metadata(body)), response(200), response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(204));
    await storage.deleteRecoverable(originalOne, deadline);
    expect(transport.requests[1]).toMatchObject({ method: "PUT", headers: { "x-amz-metadata-directive": "REPLACE", "x-amz-meta-sha256": sha256(body), "x-amz-meta-media-type": "image/png", "x-amz-meta-recoverable-until": deadline.toISOString() } });
    transport.responses.push(response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(200, {}, stream(body)), response(200), response(204));
    await expect(storage.restore(originalOne)).resolves.toBe(true);
    transport.responses.push(response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }));
    await expect(storage.reclaim(originalOne, new Date("2026-08-24T12:04:59.000Z"))).rejects.toThrow("GRACE");
    transport.responses.push(response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(204));
    await expect(storage.reclaim(originalOne, deadline)).resolves.toBe(true);
  });

  it("retries safely when recovery copy succeeded before source deletion failed", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport); const body = bytes("one"); const deadline = new Date("2026-08-24T12:05:00.000Z");
    transport.responses.push(response(200, metadata(body)), response(200), response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(503));
    await expect(storage.deleteRecoverable(originalOne, deadline)).rejects.toThrow("UNAVAILABLE");
    transport.responses.push(response(200, metadata(body)), response(200), response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(204));
    await expect(storage.deleteRecoverable(originalOne, deadline)).resolves.toBeUndefined();
    expect(transport.requests.filter(({ method, key }) => method === "PUT" && key !== originalOne)).toHaveLength(2);
  });

  it("reconciles an exact existing original on restore retry and then deletes recovery", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport); const body = bytes("one"); const deadline = new Date("2026-08-24T12:05:00.000Z");
    transport.responses.push(
      response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }),
      response(200, { ...metadata(body), "x-amz-meta-recoverable-until": deadline.toISOString() }), response(200, {}, stream(body)),
      response(412), response(200, metadata(body)), response(200, {}, stream(body)), response(204)
    );
    await expect(storage.restore(originalOne)).resolves.toBe(true);
    expect(transport.requests.at(-1)).toMatchObject({ method: "DELETE" });
  });

  it("uses a validated lexical start-after cursor across two inventory pages", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport); const one = bytes("one"); const two = bytes("two"); const prefix = `tenants/${scope.tenantId}/sites/${scope.siteId}/originals/`;
    transport.responses.push(response(200, {}, streamText(listPage(originalOne, one.byteLength, true))), response(200, metadata(one)));
    const first = await storage.inventory(prefix, 1);
    expect(first).toMatchObject({ nextCursor: originalOne });
    transport.responses.push(response(200, {}, streamText(listPage(originalTwo, two.byteLength, false))), response(200, metadata(two)));
    const second = await storage.inventory(prefix, 1, first.nextCursor);
    expect(second.objects.map(({ key }) => key)).toEqual([originalTwo]);
    expect(transport.requests[2]?.query).toMatchObject({ "start-after": originalOne });
    await expect(storage.inventory(prefix, 1, pendingKey)).rejects.toThrow("CURSOR");
  });

  it("signs immutable browser-safe upload headers only through the PostgreSQL issuer", async () => {
    const storage = adapter(new RecordingTransport(), signing());
    const issuer = new PostgresMediaUploadIntentSigner(databaseFor(binding()), storage);
    const upload = await issuer.sign(fullScope(), binding().intentId, 600);
    expect(upload).toMatchObject({ key: pendingKey, method: "PUT", headers: { "if-none-match": "*", "content-type": "image/png" } });
    expect(upload.headers).not.toHaveProperty("content-length");
    expect(upload.headers).not.toHaveProperty("x-amz-meta-expected-size");
    expect(new URL(upload.url).searchParams.get("X-Amz-Expires")).toBe("120");
    expect(new URL(upload.url).searchParams.get("x-amz-meta-expected-size")).toBe("42");
    expect(new URL(upload.url).searchParams.get("X-Amz-Content-Sha256")).toBe("UNSIGNED-PAYLOAD");
    expect(new URL(upload.url).searchParams.get("X-Amz-SignedHeaders")).toBe("content-type;host;if-none-match;x-navocms-upload-intent;x-navocms-upload-ttl");
    expect(canonicalUrl(await awsSdkPresign(binding(), 120))).toBe(AWS_SDK_V3_SIGV4_VECTOR);
    expect(canonicalUrl(upload.url)).toBe(AWS_SDK_V3_SIGV4_VECTOR);
    expect(() => storage.signDirectUploadWithCapability(binding(), 60, Symbol("forged"))).toThrow("FORBIDDEN");
    await expect(new PostgresMediaUploadIntentSigner(databaseFor({ ...binding(), expiresAt: "not-a-date" }), storage).sign(fullScope(), binding().intentId, 60)).rejects.toThrow("INTENT");
    await expect(new PostgresMediaUploadIntentSigner(databaseFor({ ...binding(), expectedSize: MEDIA_LIMITS.maxBytes + 1 }), storage).sign(fullScope(), binding().intentId, 60)).rejects.toThrow("INTENT");
    await expect(issuer.sign(fullScope(), binding().intentId, 901)).rejects.toThrow("INTENT");
  });

  it("rejects provider failures without provider headers, URLs, or credentials", async () => {
    const transport = new RecordingTransport(); const storage = adapter(transport);
    transport.responses.push(response(503, { "x-provider-secret": "must-not-leak" }));
    await expect(storage.head(pendingKey)).rejects.toThrow("STORAGE_PROVIDER_UNAVAILABLE");
  });
});

class RecordingTransport implements S3Transport {
  readonly requests: Array<Parameters<S3Transport["request"]>[0]> = [];
  readonly responses: S3TransportResponse[] = [];
  async request(input: Parameters<S3Transport["request"]>[0]): Promise<S3TransportResponse> { this.requests.push(input); return this.responses.shift() ?? response(200); }
}
function adapter(transport: S3Transport, directUploadSigning?: { endpoint: string; region: string; accessKeyId: string; secretAccessKey: string }) { return new S3CompatibleMediaStorage({ ...scope, bucket: "navocms-media", transport, clock: () => now, ...(directUploadSigning ? { directUploadSigning } : {}) }); }
function signing() { return { endpoint: "https://r2.example.test", region: "auto", accessKeyId: "AKIDEXAMPLE", secretAccessKey: "secret-for-test-only" }; }
function binding() { return { intentId: pendingKey.split("/").at(-1)!, storageKey: pendingKey, expectedSha256: "a".repeat(64), expectedSize: 42, expectedMediaType: "image/png" as const, expiresAt: "2026-08-24T12:02:00.000Z" }; }
function fullScope() { return { ...scope, principalId: "44444444-4444-4444-8444-444444444444", principalKind: "human" as const }; }
function databaseFor(intent: ReturnType<typeof binding>): PostgresDatabase {
  return {
    async withScope<T>(_scope: unknown, operation: (client: SqlClient) => Promise<T>): Promise<T> {
      return operation({ query: async () => ({ rows: [{ id: intent.intentId, storage_key: intent.storageKey, expected_sha256: intent.expectedSha256, expected_size: intent.expectedSize, expected_media_type: intent.expectedMediaType, expires_at: intent.expiresAt, finalized_at: null }] }) } as SqlClient);
    }
  } as unknown as PostgresDatabase;
}
async function awsSdkPresign(intent: ReturnType<typeof binding>, expiresIn: number): Promise<string> {
  const headers = { host: "r2.example.test", "content-type": intent.expectedMediaType, "if-none-match": "*", "x-amz-meta-sha256": intent.expectedSha256, "x-amz-meta-media-type": intent.expectedMediaType, "x-amz-meta-expected-size": String(intent.expectedSize), "X-Amz-Content-Sha256": "UNSIGNED-PAYLOAD", "x-navocms-upload-intent": intent.intentId, "x-navocms-upload-ttl": String(expiresIn) };
  const request = new HttpRequest({ protocol: "https:", hostname: "r2.example.test", method: "PUT", path: `/navocms-media/${intent.storageKey}`, headers });
  const signed = await new SignatureV4({ credentials: { accessKeyId: "AKIDEXAMPLE", secretAccessKey: "secret-for-test-only" }, region: "auto", service: "s3", sha256: Sha256 }).presign(request, { expiresIn, signingDate: now });
  const query = new URLSearchParams();
  for (const [name, value] of Object.entries(signed.query ?? {})) query.set(name, String(value));
  return `${signed.protocol}//${signed.hostname}${signed.path}?${query.toString()}`;
}
function canonicalUrl(value: string): string { const url = new URL(value); const query = [...url.searchParams.entries()].sort(([left], [right]) => left.localeCompare(right)); url.search = new URLSearchParams(query).toString(); return url.toString(); }
function bytes(value: string): Uint8Array { return new TextEncoder().encode(value); }
function metadata(body: Uint8Array, mediaType = "image/png"): Record<string, string> { return { "content-length": String(body.byteLength), "x-amz-meta-sha256": sha256(body), "x-amz-meta-media-type": mediaType }; }
function response(status: number, headers: Record<string, string> = {}, body?: AsyncIterable<Uint8Array>, abort?: () => void): S3TransportResponse { return { status, headers, ...(body ? { body } : {}), ...(abort ? { abort } : {}) }; }
function listPage(key: string, size: number, truncated: boolean): string { return `<ListBucketResult><Contents><Key>${key}</Key><Size>${size}</Size></Contents><IsTruncated>${truncated}</IsTruncated></ListBucketResult>`; }
async function* stream(...chunks: Uint8Array[]): AsyncIterable<Uint8Array> { yield* chunks; }
async function* brokenStream(): AsyncIterable<Uint8Array> { throw new Error("secret body error"); }
async function* streamText(value: string): AsyncIterable<Uint8Array> { yield bytes(value); }
